{"name": "Проверка, что нельзя создать двух пользователей с одинаковый логином (email)", "status": "passed", "description": "Проверяем, что при создании пользователя с логином, который уже используется, возвращается ошибка: код ответа 403 и сообщение, что пользователь уже существует", "steps": [{"name": "Метод создания нового пользователя - POST-запрос", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'bga14@yandex.ru', 'password': 'password1', 'name': 'username1'}"}], "start": 1732740435577, "stop": 1732740436066}], "start": 1732740435577, "stop": 1732740436067, "uuid": "d54e4b74-7664-4508-bb8c-c77094e12dfa", "historyId": "3057f9affbc62abb9589b983d965be07", "testCaseId": "3057f9affbc62abb9589b983d965be07", "fullName": "tests.users.test_create_user.TestCreateUser#test_post_create_user_impossible_create_two_user_with_same_login", "labels": [{"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "Tony-Ocean"}, {"name": "thread", "value": "20844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_create_user"}]}